# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZalandoFastSearchSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZalandoFastSearchSwift
  pod 'MaterialComponents/TextFields'
  pod 'MaterialComponents/Buttons'
  
  pod 'FlexLayout'
  pod 'PinLayout'
  pod 'SnapKit'
  pod 'Moya'
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'ZalandoFastSearchSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZalandoFastSearchSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
